### ISSUE TITLE
question about irc notification in Drone CI of cmc repo

### ISSUE THREAD

**Issue by fracting** [compojoom/cmc#3]
Hi, apologize for off topic question, but I'm not able to find a better place yet :(

I'm trying to get Drone CI irc notification working, I searched github and found your repo with Drone CI irc notification enabled, does it really worked for you and is it still working?

Thank you!

**Comment by yvesh** [comment]
Hi Qian,
 
yes it's still working, just checked with another extension.
 
IRC part of the config:
 
irc: 
 prefix: build 
 nick: compodronebot 
 channel: compojoom 
 server: 
 host: chat.freenode.net 
 port: 6667 

 
Drone is running as current version (0.4). Carefull with the packages.. This is quite a mess, if you download the deb file etc. you are on an old version. 
 
You need to get the docker irc plugin: docker pull plugins/drone-irc

At the GitHub repo you find a test (you can run it from the cli without commit):

https://github.com/drone-plugins/drone-irc
 
Cheers,
Yves

**Comment by fracting** [comment]
Hi Yves,

Thanks a lot for your nice help!
After having a working reference, I also made my Drone server working with irc plugin. It's not completely clear what was wrong to me yet, but as far as I can found:
- Drone add `environment` in the `irc` section, it will confuse the irc plugin and the irc plugin will fail silently
- Make sure .drone.sec match .drone.yml, otherwise the irc plugin also fails silently.

Thank you and Merry Christmas :)
